name: buqi
description: "my first application"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.2.0
  fluro: ^2.0.5
  weather_animation: ^1.0.1
  permission_handler: ^11.2.0
  geolocator: ^10.1.0
  location: ^5.0.3
  geocoding: ^2.1.1
  http: ^1.2.0
  shared_preferences: ^2.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
